### ISSUE TITLE
Abstract-Initial Version

### ISSUE THREAD

**Issue by mkhoshle** [Becksteinlab/Scipy2017#1]
The initial version of the abstract is ready.

**Comment by orbeckst** [comment]
Ok, will look in more detail. When is the deadline?

**Comment by mkhoshle** [comment]
It is March 27th.

**Comment by mkhoshle** [comment]
I just contacted them.
Talk proposals for the conference must be submitted by **March 24th**. 
Once talk is accepted, a **8 page** paper should be submitted by **May 24h**.
Talk acceptances will be made on **May 3rd**.
