### ISSUE TITLE
make abstract separate markdown file

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/Scipy2017#2]
I think abstract submission will be pure text only. Make the abstract a stand-alone text file `abstract.md` and we write it in simple markdown. This will also make reviewing/amending easier because we can see it directly on GitHub instead of having to run LaTeX.

**Comment by mkhoshle** [comment]
Ok, I removed the Tex files and added the abstract in .md format. There is a sample paper in conference web page (https://github.com/mkhoshle/scipy_proceedings) which is in .rst format. But that is for the last year, the dates are not updated and I am not sure if I should put everything in that format or not. I will contact them and ask.

**Comment by orbeckst** [comment]
Use rest – that's perfectly fine.

Oliver

> On 16 Mar, 2017, at 10:48, Mahzad Khoshlessan <notifications@github.com> wrote:
> 
> Ok, I removed the Tex files and added the abstract in .md format. There is a sample paper in conference web page (https://github.com/mkhoshle/scipy_proceedings) which is in .rst format. But that is for the last year, the dates are not updated and I am not sure if I should put everything in that format or not. I will contact them and ask.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by mkhoshle** [comment]
I prepared the abstract in the requested form of the conference. 
They need a brief abstract and a long description (https://www.eiseverywhere.com/ehome/220975/493425/) and also encouraged any link to the source code or full paper. So I have included them.

**Comment by mkhoshle** [comment]
@orbeckst, the abstract is ready and updated now.
Thanks.

**Comment by orbeckst** [comment]
Thanks, will have a look.

**Comment by orbeckst** [comment]
I pushed my edits. Please have a look.
